<?php

namespace Aether\Providers;

use Aether\Config;
use Aether\AetherConfig;

class ConfigProvider extends Provider
{
    public function register()
    {
        $this->registerAppConfig();

        $this->registerAetherConfig();
    }

    protected function registerAppConfig()
    {
        // Load the application config and bind it to the service locator, so
        // that we can easily access it anywhere in the code using the
        // `config()` helper function.
        $this->aether->singleton('config', function ($aether) {
            return new Config($aether['projectRoot']);
        });
    }

    protected function registerAetherConfig()
    {
        $this->aether->singleton('aetherConfig', function ($aether) {
            $projectRoot = $aether['projectRoot'];

            if (! file_exists($configPath = $projectRoot.'config/autogenerated.config.xml')) {
                $configPath = $projectRoot.'config/aether.config.xml';
            }

            $aetherConfig = new AetherConfig($configPath);

            if ($aether->bound('parsedUrl')) {
                $aetherConfig->matchUrl($aether['parsedUrl']);
            }

            return $aetherConfig;
        });
    }
}
