<?php

namespace Aether\Console\Commands;

use Aether\Console\Command;

class ConfigClearCommand extends Command
{
    protected $signature = 'config:clear';

    protected $description = 'Clear the compiled config files';

    public function handle()
    {
        if (file_exists($file = "{$this->aether['projectRoot']}config/autogenerated.config.xml")) {
            unlink($file);
        }

        if (file_exists($file = "{$this->aether['projectRoot']}config/compiled.php")) {
            unlink($file);
        }

        $this->info('Config cleared.');
    }
}
