<?php

namespace Aether\Console\Commands;

use Aether\Aether;
use Aether\Config;
use Aether\AetherConfig;
use Aether\Console\Command;

class ConfigGenerateCommand extends Command
{
    protected $signature = 'config:generate';

    protected $description = 'Generate compiled configuration files.';

    public function handle()
    {
        $this->call('config:clear');

        // Delete the already resolved instances, otherwise it will just write
        // what's already written.
        $this->aether->forgetInstance('config');
        $this->aether->forgetInstance('aetherConfig');

        $this->writeCompiledConfig($this->aether);
        $this->writeAetherConfig($this->aether);

        $this->writeCompiledConfig();

        $this->writeAetherConfig();

        $this->info('Compiled configuration files have been generated.');

        $this->info("Environment: {$this->aether['config']['app.env']}");
    }

    protected function writeCompiledConfig()
    {
        $this->aether['config']->saveToFile(
            "{$this->aether['projectRoot']}config/compiled.php"
        );
    }

    protected function writeAetherConfig()
    {
        $this->aether['aetherConfig']->saveToFile(
            "{$this->aether['projectRoot']}config/autogenerated.config.xml"
        );
    }
}
