<?php

namespace Aether\Console\Commands;

use Aether\Aether;
use Aether\Config;
use Aether\AetherConfig;
use Aether\Console\Command;

class ConfigGenerateCommand extends Command
{
    protected $signature = 'config:generate';

    protected $description = 'Generate compiled configuration files.';

    public function handle()
    {
        $this->call('config:clear');

        $aether = $this->freshAether();

        $this->writeCompiledConfig($aether);
        $this->writeAetherConfig($aether);

        $this->info('Compiled configuration files have been generated.');

        $this->info("Environment: {$aether['config']['app.env']}");
    }

    protected function freshAether()
    {
        $aether = new Aether($this->aether['projectRoot']);

        $aether->bootstrapWith([
            \Aether\Bootstrap\RegisterProviders::class,
        ]);

        return $aether;
    }

    protected function writeCompiledConfig($aether)
    {
        $aether['config']->saveToFile(
            "{$aether['projectRoot']}config/compiled.php"
        );
    }

    protected function writeAetherConfig($aether)
    {
        $aether['aetherConfig']->saveToFile(
            "{$aether['projectRoot']}config/autogenerated.config.xml"
        );
    }
}
